### ISSUE TITLE
Dark Mode Labels are not visible.

### ISSUE THREAD

**Issue by jkuepker** [hobbes3/viz_halo#1]
Please account for the new dark mode in 7.2.  Since the labels are a static color it i hard to see the black text on a dark background.  Something like font_color=if(dark_mode="true", "white", "black").  Or just make it selectable.  Thank you.

**Comment by hobbes3** [comment]
I'll add a `label_color` option for the viz. Defaults to `"black"`.

**Comment by hobbes3** [comment]
Created three new formatting options: `label_text_color`, `label_line_color`, and `label_dot_color`. Please download version 1.1.2 from https://splunkbase.splunk.com/app/3514.
